const wordList = [
  { word: "apple", hint: "A fruit that is often red or green" },
  { word: "banana", hint: "A long, curved fruit with yellow skin" },
  { word: "cat", hint: "A small, furry animal that says 'meow'" },
  { word: "dog", hint: "A loyal animal that is often kept as a pet" },
  { word: "elephant", hint: "A large animal with a long trunk and big ears" },
  { word: "flower", hint: "A colorful plant that is often given as a gift" },
  { word: "grape", hint: "A small, juicy fruit that grows in bunches" },
  { word: "house", hint: "A place where people live" },
  { word: "ice cream", hint: "A frozen dessert made from milk or cream" },
  { word: "jacket", hint: "A piece of clothing worn on the upper body" },
  { word: "kangaroo", hint: "A hopping marsupial from Australia" },
  { word: "lion", hint: "A large, fierce cat with a mane" },
  {
    word: "mountain",
    hint: "A tall landform that rises above the surrounding land",
  },
  { word: "nose", hint: "A facial feature used for smelling" },
  { word: "octopus", hint: "A sea creature with eight arms and a soft body" },
  {
    word: "pizza",
    hint: "A popular Italian dish with cheese and toppings on a crust",
  },
  { word: "queen", hint: "A female ruler of a kingdom" },
  { word: "rainbow", hint: "An arch of colors in the sky after rain" },
  { word: "sunflower", hint: "A tall plant with large yellow flowers" },
  { word: "turtle", hint: "A slow-moving reptile with a shell" },
  { word: "umbrella", hint: "An object used to protect from rain or sun" },
  {
    word: "violin",
    hint: "A musical instrument with strings played with a bow",
  },
  { word: "watermelon", hint: "A large fruit with a green rind and red flesh" },
  {
    word: "xylophone",
    hint: "A musical instrument with wooden bars and mallets",
  },
  { word: "yacht", hint: "A luxurious boat used for recreation or racing" },
  { word: "zebra", hint: "A striped African animal related to horses" },
  { word: "airplane", hint: "A vehicle that flies in the air" },
  { word: "basketball", hint: "A sport played with a ball and hoop" },
  { word: "carrot", hint: "A root vegetable that is often orange" },
  {
    word: "dolphin",
    hint: "A marine mammal known for its intelligence and playfulness",
  },
  { word: "eleven", hint: "The number after ten" },
  { word: "football", hint: "A sport played with a ball and goalposts" },
  {
    word: "guitar",
    hint: "A musical instrument with strings played with the fingers",
  },
  {
    word: "hamburger",
    hint: "A popular food consisting of a cooked meat patty in a bun",
  },
  { word: "island", hint: "A landform surrounded by water" },
  { word: "jellyfish", hint: "A gelatinous sea creature with tentacles" },
  { word: "kite", hint: "An object flown in the air on a string" },
  { word: "lemon", hint: "A sour citrus fruit" },
  { word: "mushroom", hint: "A type of fungus used in cooking" },
  { word: "notebook", hint: "A bound collection of paper used for writing" },
  { word: "ocean", hint: "A large body of saltwater" },
  { word: "pencil", hint: "A writing utensil with a graphite core" },
  { word: "quail", hint: "A small, ground-dwelling bird" },
  { word: "robot", hint: "A machine that can perform tasks automatically" },
  { word: "strawberry", hint: "A juicy red fruit with small seeds" },
  { word: "tiger", hint: "A large, striped feline" },
  {
    word: "umbilical cord",
    hint: "A flexible cord that connects a fetus to the placenta",
  },
  { word: "violinist", hint: "A musician who plays the violin" },
  {
    word: "waterfall",
    hint: "A natural feature where water flows over a steep drop",
  },
  { word: "xylophonist", hint: "A musician who plays the xylophone" },
  {
    word: "yoga",
    hint: "A practice that combines physical postures, breathing, and relaxation",
  },
  {
    word: "zealot",
    hint: "A person who is fanatical and uncompromising in their beliefs",
  },
];
